"use client";





import Link from "next/link";
import { useAuth } from "@/context/AuthContext";
import { useRouter } from "next/navigation";
import { useEffect } from "react";
import { motion } from "framer-motion";

export default function Home() {
  const { isAuthenticated } = useAuth();
  const router = useRouter();

  useEffect(() => {
    if (isAuthenticated) {
      router.push("/speaking/part1");
    }
  }, [isAuthenticated, router]);

  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.1,
        delayChildren: 0.2,
      },
    },
  };

  const itemVariants = {
    hidden: { opacity: 0, y: 20 },
    visible: {
      opacity: 1,
      y: 0,
      transition: { duration: 0.8 },
    },
  };

  return (
    <div className="min-h-screen bg-gradient-to-b from-primary to-primary/90 text-white">
      {/* Navbar */}
      <nav className="flex items-center justify-between px-6 py-6 lg:px-12">
        <div className="text-2xl font-bold text-accent">IELTS AI</div>
        <div className="flex gap-4">
          <Link
            href="/login"
            className="rounded-full px-6 py-2 text-accent hover:bg-white/10 transition"
          >
            Sign In
          </Link>
          <Link
            href="/register"
            className="rounded-full px-6 py-2 bg-accent text-primary font-semibold hover:opacity-90 transition"
          >
            Get Started
          </Link>
        </div>
      </nav>

      {/* Hero Section */}
      <motion.div
        className="mx-auto max-w-6xl px-6 py-20 lg:px-12"
        variants={containerVariants}
        initial="hidden"
        animate="visible"
      >
        <motion.div variants={itemVariants} className="text-center">
          <h1 className="text-5xl lg:text-7xl font-bold text-balance mb-6">
            Master IELTS Speaking with AI
          </h1>
          <p className="text-xl lg:text-2xl text-gray-200 text-balance mb-8">
            Get instant feedback on your pronunciation, fluency, and vocabulary.
            Practice unlimited speaking tests with AI-powered evaluation.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link
              href="/register"
              className="rounded-full px-8 py-3 bg-accent text-primary font-semibold hover:opacity-90 transition inline-block text-center"
            >
              Start Free Trial
            </Link>
            <button className="rounded-full px-8 py-3 border-2 border-accent text-accent font-semibold hover:bg-white/10 transition">
              Watch Demo
            </button>
          </div>
        </motion.div>

        {/* Features Grid */}
        <motion.div
          variants={itemVariants}
          className="mt-24 grid md:grid-cols-3 gap-8"
        >
          {[
            {
              title: "AI-Powered Questions",
              description:
                "Get unique questions generated by AI for each practice session",
              icon: "рџ¤–",
            },
            {
              title: "Voice Recording",
              description:
                "Record your answers with crystal-clear audio capture and processing",
              icon: "рџЋ¤",
            },
            {
              title: "Instant Scores",
              description:
                "Receive detailed feedback on fluency, vocabulary, grammar, and pronunciation",
              icon: "вљЎ",
            },
          ].map((feature, i) => (
            <motion.div
              key={i}
              variants={itemVariants}
              className="card-base p-8 text-center hover:shadow-xl transition"
            >
              <div className="text-5xl mb-4">{feature.icon}</div>
              <h3 className="text-xl font-bold text-primary mb-3">
                {feature.title}
              </h3>
              <p className="text-muted-foreground">{feature.description}</p>
            </motion.div>
          ))}
        </motion.div>

        {/* Stats Section */}
        <motion.div
          variants={itemVariants}
          className="mt-24 grid md:grid-cols-3 gap-8 text-center"
        >
          {[
            { value: "10K+", label: "Active Users" },
            { value: "1M+", label: "Practice Sessions" },
            { value: "95%", label: "Success Rate" },
          ].map((stat, i) => (
            <div key={i}>
              <div className="text-4xl font-bold text-accent">{stat.value}</div>
              <p className="text-gray-300">{stat.label}</p>
            </div>
          ))}
        </motion.div>

        {/* CTA Section */}
        <motion.div
          variants={itemVariants}
          className="mt-24 text-center bg-white/10 backdrop-blur rounded-2xl p-12"
        >
          <h2 className="text-3xl font-bold mb-4">Ready to improve your IELTS speaking?</h2>
          <p className="text-gray-200 mb-8">
            Join thousands of students who have already improved their band scores
          </p>
          <Link
            href="/register"
            className="rounded-full px-8 py-3 bg-accent text-primary font-semibold hover:opacity-90 transition inline-block"
          >
            Start Free Trial Now
          </Link>
        </motion.div>
      </motion.div>

      {/* Footer */}
      <footer className="border-t border-white/10 px-6 py-12 text-center text-gray-400 lg:px-12">
        <p>В© 2024 IELTS Speaking AI. All rights reserved.</p>
      </footer>
    </div>
  );
}